Assignment-06-Fashionz
Paranthaman-Palani/UI-Training pull request #1
Opened 2023-02-23 05:45 UTC by Paranthaman-Palani

2023-02-23 06:02 UTC, csekharb requested changes
please review the changes

2023-02-23 06:02 UTC, csekharb commented on Assignment-06-Fashionz/index.html
> +        <div class="section-row-bottom">
can add comments individual sections rather than the entire block

2023-02-23 06:02 UTC, csekharb commented on Assignment-06-Fashionz/index.html
> +
Why can't we use a section tag here ?

2023-02-23 06:02 UTC, csekharb commented on Assignment-06-Fashionz/index.html
> +<!-----------------------------------------------------------START:: Footer-Navigation --------------------------------------------------------------------->
When you've used header tag, why not footer ?

2023-02-23 06:24 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +    <title>Document</title>
Okay

2023-02-23 09:31 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +    <link rel="stylesheet" href="styles/style.css">
ok

2023-02-23 11:46 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +          <span></span>
to design profile icon

2023-02-23 11:47 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +                <li><a href="">My Account</a></li>
ok

2023-02-23 11:47 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +                    <p>₹ 850</p>
ok

2023-02-23 11:47 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +                   <img class="icon" src="assets/icons/download.svg" alt="">
ok

2023-02-23 11:47 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +                    <button><h5>ADD TO CART</h5></button>
ok

2023-02-23 11:48 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +<!-----------------------------------------------------------START:: Section-container-bottom --------------------------------------------------------------------->
ok removed

2023-02-23 11:48 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +   font-family: "Roboto",sans-serif;
ok

2023-02-23 11:48 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +    background-color: #d8d8d8;
ok

2023-02-23 11:49 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +                font-family: "Roboto",sans-serif;
ok removed

2023-02-23 11:49 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +                width:17rem;
ok

2023-02-23 11:50 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +                display: none;
to dispaly the menu while hovering the profile icon

2023-02-23 11:50 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +    color: hwb(0 67% 33%);
ok

2023-02-23 11:50 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +border-color: #000000;
ok

2023-02-23 11:51 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/styles/style.css
> +    display: none;
to get color filled star effect  while hovering

2023-02-23 11:51 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +        <div class="section-row-bottom">
ok

2023-02-23 11:51 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +
ok

2023-02-23 11:51 UTC, Paranthaman-Palani commented on Assignment-06-Fashionz/index.html
> +<!-----------------------------------------------------------START:: Footer-Navigation --------------------------------------------------------------------->
ok

2023-02-24 06:36 UTC, csekharb approved these changes
Looks Good

2023-02-24 06:37 UTC, merged